// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTcxWmGleskjW94fZwTTnokmYtg7teXQk',
    appId: '1:897161998123:web:52c85184962dbdf8f5df6e',
    messagingSenderId: '897161998123',
    projectId: 'duniyar-hausawa',
    authDomain: 'duniyar-hausawa.firebaseapp.com',
    storageBucket: 'duniyar-hausawa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTcxWmGleskjW94fZwTTnokmYtg7teXQk',
    appId: '1:897161998123:android:52c85184962dbdf8f5df6e',
    messagingSenderId: '897161998123',
    projectId: 'duniyar-hausawa',
    storageBucket: 'duniyar-hausawa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTcxWmGleskjW94fZwTTnokmYtg7teXQk',
    appId: '1:897161998123:ios:52c85184962dbdf8f5df6e',
    messagingSenderId: '897161998123',
    projectId: 'duniyar-hausawa',
    storageBucket: 'duniyar-hausawa.firebasestorage.app',
    iosBundleId: 'com.example.duniyarHausawa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTcxWmGleskjW94fZwTTnokmYtg7teXQk',
    appId: '1:897161998123:ios:52c85184962dbdf8f5df6e',
    messagingSenderId: '897161998123',
    projectId: 'duniyar-hausawa',
    storageBucket: 'duniyar-hausawa.firebasestorage.app',
    iosBundleId: 'com.example.duniyarHausawa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTcxWmGleskjW94fZwTTnokmYtg7teXQk',
    appId: '1:897161998123:web:52c85184962dbdf8f5df6e',
    messagingSenderId: '897161998123',
    projectId: 'duniyar-hausawa',
    authDomain: 'duniyar-hausawa.firebaseapp.com',
    storageBucket: 'duniyar-hausawa.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBTcxWmGleskjW94fZwTTnokmYtg7teXQk',
    appId: '1:897161998123:web:52c85184962dbdf8f5df6e',
    messagingSenderId: '897161998123',
    projectId: 'duniyar-hausawa',
    authDomain: 'duniyar-hausawa.firebaseapp.com',
    storageBucket: 'duniyar-hausawa.firebasestorage.app',
  );
}